name: First-Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: 
        run: echo "Welcome to git hub actions"
      
      - name: create test file
        run: echo ""This second line" >> test.txt

      - name: list a file
        run: ls -l
